on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: whatsapp-notify
        id: whatsapp-notify
        env:
          account_sid: ACe60c1e03fe831238b85dd4af08627c22
          auth_token: 9bde7204fb2fb486e7419e068da955dc
          to_whatsapp_no: 9477683161


        
      
      - name : Run
        run: |
          echo 'Start!'